alias gs='git status -sb'
alias gc='git commit'
alias ga='git add -up'
alias develop='git checkout develop'
alias developp='develop && pull' 
alias master='git checkout master'
alias masterp='master && pull'
